# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # We only support 3.10+.
  jobs:
    build:
      epub:
        - mkdir -p _temp
        - mkdir -p $READTHEDOCS_OUTPUT/epub
        - python -m sphinx -T -W --keep-going -b epub -d _build/doctrees -D language=en -D epub_build=True -D version="test" ./docs _temp
        - mv _temp/*.epub $READTHEDOCS_OUTPUT/epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - full
